### ISSUE TITLE
Problems with the setup / Probleme beim einrichten. 

### ISSUE THREAD

**Issue by samokles** [StephanU/MyGekko#77]
English: 

Hi Stephan, 

Thank you very much for the effort to get the data from Mygekko into HA.

I followed your installation instructions exactly and was able to enter my username, API key and Gekko ID. There was no error message when logging in. The data seems to fit. However, the integration keeps telling me "No devices or entities" setup failed, will try again. Plus service at Mygekko is active as I have been using the API for Alexa for years.   

Do you have a tip for me on what I could be doing wrong? 

------

Deutsch: 

Hi Stephan, 

vielen lieben Dank für die Mühe die Daten von Mygekko in HA zu bekommen.

Ich bin genau deiner Installationsanweisung gefolgt und konnte meinen Nutzernamen, API Key und Gekko ID eingeben. Es kam keine Fehlermeldung bei der Anmeldung. Die Daten scheinen zu passen. Jedoch meldet mir die Integration die ganze Zeit "Keine Geräte oder Entitäten" Einrichtung fehlgeschlagen, wird erneut versucht. Plus Service bei Mygekko ist aktiv, da ich schon seit Jahren die API für Alexa nutze.   

Hast du da einen Tipp für mich, was ich falsch machen könnte?

**Comment by StephanU** [comment]
Hi, 
which Version of MyGekko do you have?
The current implementation only worked with a MyGekko Slide2 (Version 596610). Now it also works for MyGekko Slide2 (Version 680016).
Please try the latest release (0.0.29).

**Comment by StephanU** [comment]
Please update to the newest version and write a new issue und case you still have problems.
